version: '2'
services:
  mongo:
    image: mongo
    command:
      - --smallfiles
    expose:
      - "27017"
  uptime:
    image: katsanva/uptime
    ports:
      - 80:8082
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - default
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - SERVICE_USERNAME=guest
      - SERVICE_PASSWORD=blabla
