url: 'http://localhost:8082'

mongodb:
  server:   ::MONGODB_HOST_PORT::
  database: ::MONGODB_DATABASE::
  user:     ::MONGODB_USER::
  password: ::MONGODB_PASSWORD::
  #connectionString:  # alternative to setting server, database, user and password separately

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:8082/api' # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/fzaninotto/uptime)

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: true

plugins:
  - ./plugins/console
  - ./plugins/patternMatcher
  - ./plugins/httpOptions
  - ./plugins/basicAuth

basicAuth:
  username: ::AUTH_USER::
  password: ::AUTH_PASSWORD::
verbose: false # only used in dev
